baseURL: 'https://example.org/'
languageCode: 'en-us'
title: Paper Coat's Blog
theme: PaperMod

mainsections: ["reviews"]
enableEmoji: true

params:
  defaultTheme: dark
  author: Paper Coat
  DateFormat: "January 2, 2006"

  ShowReadingTime: true
  ShowPostNavLinks: true
  UseHugoToc: true
  showtoc: true
  tocopen: false

  homeInfoParams:
    Title: "Hello Everyone" 
    Content: |
      This blog will *generally* be book reviews/opinions. Some other.
      - View content by my [identifiers](identifiers/).
      - For more information check the [About](about/) page.
taxonomies:
  tag: tags
  mystatus: mystatus
  ratings: ratings
  preference: preference
  author: authors
  content: content

menu:
  main:
    - name: ðŸ”Žï¸Ž
      url: search/
      weight: 10
    - name: Archive
      url: archives
      weight: 3
    - name: About
      url: about/
      weight: 1
    - name: Identifiers
      url: identifiers/
      weight: 2
